/** @type {import('./types.js').Pack} */
export const dialoguesSchool = {
  id: 'dialogues-school',
  slug: 'dialogues-school',
  icon: 'book',
  titleAr: 'محادثات: في المدرسة',
  titleEn: 'Dialogues: At School',
  descAr: 'خمس محادثات كاملة من الحياة المدرسية اليومية — استمع، ثم مارس دورك بصوتك.',
  descEn: 'Five full conversations from everyday school life — listen, then practice your side out loud.',
  category: 'dialogues',
  categoryAr: 'محادثات',
  categoryEn: 'Dialogues',
  releaseMonth: '2026-10',
  access: 'premium',
  price: 1000,
  currency: 'NGN',
  difficulty: 'elementary',
  status: 'published', // flip to 'published' once you've reviewed the Arabic below
  type: 'dialogue',
  themLabelAr: 'المعلم',
  themLabelEn: 'Teacher',
  youLabelAr: 'الطالب',
  youLabelEn: 'Student',
  lessons: [
    {
      id: 'sch-01',
      titleAr: 'اليوم الأول في المدرسة',
      titleEn: 'First Day at School',
      turns: [
        { speaker: 'them', ar: 'صباح الخير، أنت طالب جديد، صحيح؟', en: 'Good morning, you are a new student, right?', audio: './audio/dialogues-school/sch-01-t0.mp3' },
        { speaker: 'you',  ar: 'نعم، اسمي أحمد.', en: 'Yes, my name is Ahmed.', audio: './audio/dialogues-school/sch-01-t1.mp3' },
        { speaker: 'them', ar: 'أهلاً وسهلاً بك يا أحمد. من أين أنت؟', en: 'Welcome, Ahmed. Where are you from?', audio: './audio/dialogues-school/sch-01-t2.mp3' },
        { speaker: 'you',  ar: 'أنا من نيجيريا.', en: 'I am from Nigeria.', audio: './audio/dialogues-school/sch-01-t3.mp3' },
        { speaker: 'them', ar: 'هذا رائع. هل هذه أول مرة تدرس فيها اللغة العربية؟', en: 'That is great. Is this the first time you are studying Arabic?', audio: './audio/dialogues-school/sch-01-t4.mp3' },
        { speaker: 'you',  ar: 'نعم، أنا مبتدئ.', en: 'Yes, I am a beginner.', audio: './audio/dialogues-school/sch-01-t5.mp3' },
        { speaker: 'them', ar: 'لا تقلق، سنساعدك خطوة بخطوة. اجلس هنا من فضلك.', en: 'Do not worry, we will help you step by step. Please sit here.', audio: './audio/dialogues-school/sch-01-t6.mp3' },
        { speaker: 'you',  ar: 'شكراً جزيلاً.', en: 'Thank you very much.', audio: './audio/dialogues-school/sch-01-t7.mp3' },
        { speaker: 'them', ar: 'هذا كتابك، وهذا جدول الحصص.', en: 'This is your book, and this is the class schedule.', audio: './audio/dialogues-school/sch-01-t8.mp3' },
        { speaker: 'you',  ar: 'هل يوجد فسحة اليوم؟', en: 'Is there a break today?', audio: './audio/dialogues-school/sch-01-t9.mp3' },
        { speaker: 'them', ar: 'نعم، بعد الحصة الثانية.', en: 'Yes, after the second class.', audio: './audio/dialogues-school/sch-01-t10.mp3' },
        { speaker: 'you',  ar: 'ممتاز، شكراً على المساعدة.', en: 'Great, thank you for the help.', audio: './audio/dialogues-school/sch-01-t11.mp3' },
        { speaker: 'them', ar: 'العفو، بالتوفيق في يومك الأول!', en: 'You are welcome, good luck on your first day!', audio: './audio/dialogues-school/sch-01-t12.mp3' },
      ],
    },
    {
      id: 'sch-02',
      titleAr: 'في الفصل الدراسي',
      titleEn: 'In the Classroom',
      turns: [
        { speaker: 'them', ar: 'هل يمكن للجميع أن يفتحوا الكتاب صفحة عشرة؟', en: 'Can everyone open the book to page ten?', audio: './audio/dialogues-school/sch-02-t0.mp3' },
        { speaker: 'you',  ar: 'عفواً، ليس معي قلم.', en: 'Excuse me, I do not have a pen.', audio: './audio/dialogues-school/sch-02-t1.mp3' },
        { speaker: 'them', ar: 'لا بأس، هل تحتاج ورقة أيضاً؟', en: 'That is fine, do you need paper too?', audio: './audio/dialogues-school/sch-02-t2.mp3' },
        { speaker: 'you',  ar: 'نعم من فضلك، شكراً لك.', en: 'Yes please, thank you.', audio: './audio/dialogues-school/sch-02-t3.mp3' },
        { speaker: 'them', ar: 'تفضل. الآن، من يستطيع قراءة الجملة الأولى؟', en: 'Here you go. Now, who can read the first sentence?', audio: './audio/dialogues-school/sch-02-t4.mp3' },
        { speaker: 'you',  ar: 'أنا أستطيع، لو سمحت.', en: 'I can, if you please.', audio: './audio/dialogues-school/sch-02-t5.mp3' },
        { speaker: 'them', ar: 'تفضل، اقرأ بصوت عالٍ.', en: 'Go ahead, read it out loud.', audio: './audio/dialogues-school/sch-02-t6.mp3' },
        { speaker: 'you',  ar: 'هل قرأت بشكل صحيح؟', en: 'Did I read it correctly?', audio: './audio/dialogues-school/sch-02-t7.mp3' },
        { speaker: 'them', ar: 'نعم، أحسنت! نطقك جيد جداً.', en: 'Yes, well done! Your pronunciation is very good.', audio: './audio/dialogues-school/sch-02-t8.mp3' },
        { speaker: 'you',  ar: 'شكراً، هل يمكنني أن أسأل سؤالاً؟', en: 'Thank you, may I ask a question?', audio: './audio/dialogues-school/sch-02-t9.mp3' },
        { speaker: 'them', ar: 'بالطبع، تفضل.', en: 'Of course, go ahead.', audio: './audio/dialogues-school/sch-02-t10.mp3' },
        { speaker: 'you',  ar: 'ما معنى هذه الكلمة؟', en: 'What does this word mean?', audio: './audio/dialogues-school/sch-02-t11.mp3' },
        { speaker: 'them', ar: 'معناها "مدرسة" باللغة الإنجليزية.', en: 'It means "school" in English.', audio: './audio/dialogues-school/sch-02-t12.mp3' },
      ],
    },
    {
      id: 'sch-03',
      titleAr: 'الواجب والامتحان',
      titleEn: 'Homework and the Exam',
      turns: [
        { speaker: 'them', ar: 'هل أنهيت الواجب المنزلي؟', en: 'Did you finish the homework?', audio: './audio/dialogues-school/sch-03-t0.mp3' },
        { speaker: 'you',  ar: 'نعم، لكن كان صعباً بعض الشيء.', en: 'Yes, but it was a bit difficult.', audio: './audio/dialogues-school/sch-03-t1.mp3' },
        { speaker: 'them', ar: 'أي جزء كان صعباً؟', en: 'Which part was difficult?', audio: './audio/dialogues-school/sch-03-t2.mp3' },
        { speaker: 'you',  ar: 'السؤال الأخير، لم أفهمه جيداً.', en: 'The last question, I did not understand it well.', audio: './audio/dialogues-school/sch-03-t3.mp3' },
        { speaker: 'them', ar: 'لا تقلق، سأشرحه لك بعد الحصة.', en: 'Do not worry, I will explain it to you after class.', audio: './audio/dialogues-school/sch-03-t4.mp3' },
        { speaker: 'you',  ar: 'شكراً جزيلاً، أقدّر ذلك.', en: 'Thank you very much, I appreciate that.', audio: './audio/dialogues-school/sch-03-t5.mp3' },
        { speaker: 'them', ar: 'بالمناسبة، الامتحان يوم الاثنين القادم.', en: 'By the way, the exam is next Monday.', audio: './audio/dialogues-school/sch-03-t6.mp3' },
        { speaker: 'you',  ar: 'هل الامتحان على كل الدروس؟', en: 'Is the exam on all the lessons?', audio: './audio/dialogues-school/sch-03-t7.mp3' },
        { speaker: 'them', ar: 'لا، فقط على الوحدة الثالثة والرابعة.', en: 'No, only on unit three and four.', audio: './audio/dialogues-school/sch-03-t8.mp3' },
        { speaker: 'you',  ar: 'هل يمكنني مراجعة الدروس معك؟', en: 'Can I review the lessons with you?', audio: './audio/dialogues-school/sch-03-t9.mp3' },
        { speaker: 'them', ar: 'بالتأكيد، تعال غداً بعد الحصة الأخيرة.', en: 'Of course, come tomorrow after the last class.', audio: './audio/dialogues-school/sch-03-t10.mp3' },
        { speaker: 'you',  ar: 'حسناً، سأكون هنا.', en: 'Okay, I will be here.', audio: './audio/dialogues-school/sch-03-t11.mp3' },
        { speaker: 'them', ar: 'ممتاز، بالتوفيق في المذاكرة.', en: 'Great, good luck with studying.', audio: './audio/dialogues-school/sch-03-t12.mp3' },
      ],
    },
    {
      id: 'sch-04',
      titleAr: 'طلب الإذن',
      titleEn: 'Asking for Permission',
      turns: [
        { speaker: 'them', ar: 'نعم؟ هل تريد شيئاً؟', en: 'Yes? Do you need something?', audio: './audio/dialogues-school/sch-04-t0.mp3' },
        { speaker: 'you',  ar: 'عفواً، هل يمكنني الخروج من الفصل؟', en: 'Excuse me, may I leave the classroom?', audio: './audio/dialogues-school/sch-04-t1.mp3' },
        { speaker: 'them', ar: 'لماذا؟ هل كل شيء بخير؟', en: 'Why? Is everything okay?', audio: './audio/dialogues-school/sch-04-t2.mp3' },
        { speaker: 'you',  ar: 'نعم، أريد فقط الذهاب إلى الحمّام.', en: 'Yes, I just want to go to the bathroom.', audio: './audio/dialogues-school/sch-04-t3.mp3' },
        { speaker: 'them', ar: 'حسناً، لكن أسرع من فضلك.', en: 'Okay, but please hurry.', audio: './audio/dialogues-school/sch-04-t4.mp3' },
        { speaker: 'you',  ar: 'شكراً، سأعود بسرعة.', en: 'Thank you, I will be back quickly.', audio: './audio/dialogues-school/sch-04-t5.mp3' },
        { speaker: 'them', ar: 'هل عدت؟ اجلس في مكانك من فضلك.', en: 'Are you back? Please sit in your seat.', audio: './audio/dialogues-school/sch-04-t6.mp3' },
        { speaker: 'you',  ar: 'نعم، أنا آسف على التأخير.', en: 'Yes, I am sorry for the delay.', audio: './audio/dialogues-school/sch-04-t7.mp3' },
        { speaker: 'them', ar: 'لا بأس. هل يمكنك أن تحضر لي الكتاب من الخزانة؟', en: 'It is okay. Can you bring me the book from the cabinet?', audio: './audio/dialogues-school/sch-04-t8.mp3' },
        { speaker: 'you',  ar: 'أي كتاب تقصد؟', en: 'Which book do you mean?', audio: './audio/dialogues-school/sch-04-t9.mp3' },
        { speaker: 'them', ar: 'الكتاب الأزرق الكبير.', en: 'The big blue book.', audio: './audio/dialogues-school/sch-04-t10.mp3' },
        { speaker: 'you',  ar: 'تفضل، هذا هو الكتاب.', en: 'Here you go, this is the book.', audio: './audio/dialogues-school/sch-04-t11.mp3' },
        { speaker: 'them', ar: 'شكراً لك على المساعدة.', en: 'Thank you for the help.', audio: './audio/dialogues-school/sch-04-t12.mp3' },
      ],
    },
    {
      id: 'sch-05',
      titleAr: 'الحديث عن المكتبة',
      titleEn: 'Talking About the Library',
      turns: [
        { speaker: 'them', ar: 'هل زرت مكتبة المدرسة من قبل؟', en: 'Have you visited the school library before?', audio: './audio/dialogues-school/sch-05-t0.mp3' },
        { speaker: 'you',  ar: 'لا، لم أزرها بعد.', en: 'No, I have not visited it yet.', audio: './audio/dialogues-school/sch-05-t1.mp3' },
        { speaker: 'them', ar: 'يجب أن تذهب، فيها كتب رائعة.', en: 'You should go, it has wonderful books.', audio: './audio/dialogues-school/sch-05-t2.mp3' },
        { speaker: 'you',  ar: 'هل يمكنني استعارة كتاب من هناك؟', en: 'Can I borrow a book from there?', audio: './audio/dialogues-school/sch-05-t3.mp3' },
        { speaker: 'them', ar: 'نعم، لكن يجب أن تسجل اسمك أولاً.', en: 'Yes, but you must register your name first.', audio: './audio/dialogues-school/sch-05-t4.mp3' },
        { speaker: 'you',  ar: 'حسناً، وهل المكتبة مفتوحة كل يوم؟', en: 'Okay, and is the library open every day?', audio: './audio/dialogues-school/sch-05-t5.mp3' },
        { speaker: 'them', ar: 'نعم، من الساعة الثامنة حتى الثالثة.', en: 'Yes, from eight o\u2019clock until three.', audio: './audio/dialogues-school/sch-05-t6.mp3' },
        { speaker: 'you',  ar: 'هل تنصحني بكتاب معيّن؟', en: 'Do you recommend a specific book?', audio: './audio/dialogues-school/sch-05-t7.mp3' },
        { speaker: 'them', ar: 'جرّب هذا الكتاب عن قصص عربية قصيرة.', en: 'Try this book about short Arabic stories.', audio: './audio/dialogues-school/sch-05-t8.mp3' },
        { speaker: 'you',  ar: 'يبدو مثيراً للاهتمام. كم مدة الاستعارة المسموحة؟', en: 'It sounds interesting. What is the allowed borrowing period?', audio: './audio/dialogues-school/sch-05-t9.mp3' },
        { speaker: 'them', ar: 'يمكنك الاحتفاظ به لمدة أسبوعين.', en: 'You can keep it for two weeks.', audio: './audio/dialogues-school/sch-05-t10.mp3' },
        { speaker: 'you',  ar: 'شكراً جزيلاً، سأذهب إلى المكتبة الآن.', en: 'Thank you very much, I will go to the library now.', audio: './audio/dialogues-school/sch-05-t11.mp3' },
        { speaker: 'them', ar: 'بالتوفيق، وأخبرني رأيك في الكتاب لاحقاً.', en: 'Good luck, and tell me your opinion of the book later.', audio: './audio/dialogues-school/sch-05-t12.mp3' },
      ],
    },
  ],
  quizzes: [],
};
