/**
 * Hausa content for the "airport-english" pack.
 *
 * This is the file to open for editing Hausa text — it's just flat
 * id -> text, deliberately kept separate from the pack's main content
 * file (content/airport-english.js) so editing here never risks touching the
 * Arabic/English sentence data, ids, or quiz structure.
 *
 * sentences: lesson id -> the Hausa translation of the sentence itself
 *            (shown as a third line under the sentence, below the
 *            English translation, with no listen button — matches
 *            explainAr/explainEn's "en" text in content/airport-english.js)
 * lessons:   lesson id -> the Hausa usage NOTE (the explanation shown
 *            in the explain box, matches explainAr/explainEn)
 * quizzes:   quiz id -> { question, explain } — Hausa quiz text
 *
 * To add/change a translation: find the id below (it matches the id in
 * content/airport-english.js) and edit the text. Nothing else needs to change —
 * content/packs.js merges this file onto the pack automatically.
 */
export const sentences = {
  'air-01': 'Ina tebur na rijistar fasinjoji?',
  'air-02': 'Zan iya ganin fasfo da tikitin ka?',
  'air-03': 'Ina ƙofar shiga jirgina?',
  'air-04': 'Ina wurin bincike na tsaro?',
  'air-05': 'Ina bincikan fasfo?',
  'air-06': 'Ina da jirgin haɗi.',
  'air-07': 'Ina wurin karɓar kaya?',
  'air-08': 'Kayana sun ɓace.',
  'air-09': 'Da ƙarfe nawa za a fara shiga jirgin?',
  'air-10': 'Wannan ce ƙofar zuwa London?',
  'air-11': 'Jirgina yana da jinkiri?',
  'air-12': 'Ina so in sami kujera kusa da taga, don Allah.',
  'air-13': 'Menene iyakar nauyin kaya da aka yarda?',
  'air-14': 'Ina zan sami keken kaya?',
  'air-15': 'Akwai jinkiri a wannan jirgin?',
  'air-16': 'Ina zauren jira?',
  'air-17': 'Zan iya samun sabuwar takardar shiga jirgin?',
  'air-18': 'Ina kantin sayarwa maras haraji?',
  'air-19': 'Wannan kujera babu kowa?',
  'air-20': 'Na gode da taimakonku, ranarku ta yi kyau.',
  'air-21': 'Akwai bas mai kai fasinjoji zuwa tashar?',
  'air-22': 'Ina zan iya canza kuɗi?',
  'air-23': 'Ina na\'urar fitar da kuɗi mafi kusa?',
  'air-24': 'Akwai intanet kyauta a nan?',
  'air-25': 'Ina zan caji wayata?',
  'air-26': 'Ina buƙatar sanar da wannan kayan.',
  'air-27': 'Ina buƙatar cika fom na kwastam?',
  'air-28': 'Ina wurin shan taba?',
  'air-29': 'Akwai ɗakin sallah a wannan filin jirgin?',
  'air-30': 'Ina ɗakin shayarwa?',
  'air-31': 'Ina buƙatar keken guragu, don Allah.',
  'air-32': 'Akwai taimako ga tsofaffin fasinjoji?',
  'air-33': 'Yarona zai iya zama kusa da ni?',
  'air-34': 'Ina wurin dabbobin gida?',
  'air-35': 'An soke jirgina.',
  'air-36': 'Za ku iya sake yin mini rijista a jirgin na gaba?',
  'air-37': 'Na rasa jirgina na haɗi.',
  'air-38': 'Ina zan shigar da ƙara?',
  'air-39': 'Zan iya mayar da wannan tikiti in karɓi kuɗi?',
  'air-40': 'Tafiya lafiya!',
  'air-41': 'Yi haƙuri, wannan kujerata ce.',
  'air-42': 'Za ka iya taimaka min in sanya jakata a akwatin kaya na sama?',
  'air-43': 'Zan iya samun bargo, don Allah?',
  'air-44': 'Zan iya samun matashin kai, don Allah?',
  'air-45': 'Menene ke cikin jerin abinci yau?',
  'air-46': 'Ina so in sami kaza, don Allah.',
  'air-47': 'Zan iya samun ruwa, don Allah?',
  'air-48': 'Akwai abincin da babu nama a ciki?',
  'air-49': 'Ina bandaki?',
  'air-50': 'Akwai wani a bandaki yanzu?',
  'air-51': 'Don Allah za ka iya rage kwantar da kujerarka kaɗan?',
  'air-52': 'Har yaushe za mu sauka?',
  'air-53': 'Za ka iya kunna fitilar karatu?',
  'air-54': 'Lasifikan kunnena ba sa aiki.',
  'air-55': 'Zan iya cajin wayata a nan?',
  'air-56': 'Don Allah ku ɗaura bel ɗin kujera.',
  'air-57': 'Muna fuskantar rawar jirgi.',
  'air-58': 'Ina jin haushin ciki.',
  'air-59': 'Kuna da magani na ciwon kai?',
  'air-60': 'Na gode, wannan tafiya ce mai kyau.',
  'air-61': 'Menene dalilin ziyararka?',
  'air-62': 'Na zo ne don yawon buɗe ido.',
  'air-63': 'Na zo ne don aiki.',
  'air-64': 'Har yaushe za ka zauna?',
  'air-65': 'Zan zauna makonni biyu.',
  'air-66': 'Ina za ka sauka?',
  'air-67': 'Zan sauka a wannan otal.',
  'air-68': 'Kana da tikitin dawowa?',
  'air-69': 'Wannan shine karo na farko da ka zo?',
  'air-70': 'Don Allah ka duba kamara.',
  'air-71': 'Don Allah ka sanya yatsanka a nan.',
  'air-72': 'Ka more zamanka.',
  'air-73': 'Barka da zuwa ƙasar.',
  'air-74': 'Kana da wani abu da za ka sanar?',
  'air-75': 'Ba ni da wani abu da zan sanar.',
  'air-76': 'Don Allah ka buɗe jakarka.',
  'air-77': 'Wannan don amfanin kaina ne.',
  'air-78': 'Ina ƙofar fita?',
  'air-79': 'Ina zan sami tasi?',
  'air-80': 'Ina tebur na hayan mota?',
  'air-81': 'Ina zauren \'yan kasuwa?',
  'air-82': 'Ina da izinin shiga zauren baƙi na musamman?',
  'air-83': 'Karin kumallo na cikin zauren?',
  'air-84': 'Zan iya kawo baƙo cikin zauren?',
  'air-85': 'Ina ɗakin wanka?',
  'air-86': 'Akwai ɗakin barci a nan?',
  'air-87': 'Zan iya samun fifikon shiga jirgin da wuri?',
  'air-88': 'Ina da matsalar lafiya mai gaggawa.',
  'air-89': 'Ku kira likita, don Allah!',
  'air-90': 'Na rasa fasfona.',
  'air-91': 'Na rasa jakata ta kuɗi.',
  'air-92': 'Ina ofishin dawo da kayan da suka ɓace?',
  'air-93': 'Za ku iya taimaka min in nemo iyalina?',
  'air-94': 'Ba na jin tsaro.',
  'air-95': 'Ina ofishin \'yan sanda?',
  'air-96': 'Ina buƙatar tuntuɓar ofishin jakadancina.',
  'air-97': 'Akwai mai fassara?',
  'air-98': 'Lambar jirgina ta canza.',
  'air-99': 'Na gode da ci gaba da sanar da ni.',
  'air-100': 'Wannan manhaja ta taimake ni in yi tafiya cikin natsuwa.',
};

export const lessons = {
  'air-01': 'Ana amfani da ita idan ka isa filin jirgin sama kana neman tebur na rijistar fasinjoji na jirginka.',
  'air-02': 'Ma\'aikacin rijista ne ke faɗa maka wannan — yana da kyau ka gane ta.',
  'air-03': 'Ana amfani da ita don tambayar inda ƙofar shiga jirginka take.',
  'air-04': 'Ana amfani da ita don tambayar inda wurin bincike na tsaro yake, kafin shiga wurin ƙofofi.',
  'air-05': 'Ana amfani da ita idan ka isa wata ƙasa daban, don tambaya game da bincikan fasfo.',
  'air-06': 'Tana gaya wa ma\'aikacin cewa kana da wani jirgin daban nan take bayan wannan.',
  'air-07': 'Ana amfani da ita don tambayar inda za a karɓi kayanka bayan saukar jirgin.',
  'air-08': 'Ana faɗarta idan ba ka samu jakarka a wurin karɓar kaya ba.',
  'air-09': 'Ana amfani da ita don tambayar lokacin da za a fara shiga jirgin.',
  'air-10': 'Ana amfani da ita don tabbatar da cewa kana wurin ƙofar da ta dace kafin hawan jirgin.',
  'air-11': 'Ana amfani da ita don tambaya ko jirginka na jinkiri.',
  'air-12': 'Ana amfani da ita don neman wani nau\'in kujera na musamman a lokacin rijista ko a ƙofa.',
  'air-13': 'Ana amfani da ita don tambaya game da iyakar nauyin da aka yarda wa kayanka.',
  'air-14': 'Ana amfani da ita don tambayar inda kekunan kaya suke a filin jirgin sama.',
  'air-15': 'Wata hanya ce ta tambaya ko jirgin yana da jinkiri — tana da amfani kusa da allon lokutan tashi.',
  'air-16': 'Ana amfani da ita don tambayar inda wurin jira yake kafin hawan jirgin.',
  'air-17': 'Ana amfani da ita idan takardar shiga jirginka ta ɓace ko ta lalace.',
  'air-18': 'Ana amfani da ita don tambayar inda shaguna marasa haraji suke a filin jirgin.',
  'air-19': 'Ana amfani da ita a wurin jira ko cikin jirgin don tambaya game da kujera babu kowa.',
  'air-20': 'Kalma ce ta ladabi don kammala duk wata hira da ma\'aikatan filin jirgin sama.',
  'air-21': 'Ana amfani da ita don tambaya game da sufuri tsakanin gine-ginen filin jirgin daban-daban.',
  'air-22': 'Ana amfani da ita don tambayar inda za a canza kuɗi a filin jirgin sama.',
  'air-23': 'Ana amfani da ita don tambayar na\'urar fitar da kuɗi mafi kusa.',
  'air-24': 'Ana amfani da ita don tambaya ko akwai intanet kyauta a tashar.',
  'air-25': 'Ana amfani da ita don tambayar inda wuraren caji na waya suke.',
  'air-26': 'Ana faɗarta a kwastam idan kana ɗauke da kayan da dole a sanar da su.',
  'air-27': 'Ana amfani da ita don tambaya ko akwai buƙatar cika fom na kwastam kafin barin filin.',
  'air-28': 'Ana amfani da ita don tambayar inda aka yarda a sha taba a filin jirgin.',
  'air-29': 'Ana amfani da ita don tambaya game da wurin da aka keɓe don sallah.',
  'air-30': 'Ana amfani da ita don tambaya game da ɗakin da aka keɓe wa uwaye masu shayarwa.',
  'air-31': 'Ana amfani da ita don neman taimakon keken guragu.',
  'air-32': 'Ana amfani da ita don tambaya game da ayyukan taimako ga tsofaffin fasinjoji.',
  'air-33': 'Ana amfani da ita don neman a haɗa kujerun iyali tare.',
  'air-34': 'Ana amfani da ita don tambaya game da wurin da aka keɓe wa dabbobin gida.',
  'air-35': 'Ana amfani da ita don gaya wa ma\'aikata cewa an soke jirginka kuma kana buƙatar wani zaɓi.',
  'air-36': 'Ana amfani da ita don neman ma\'aikata su sake yin maka rijista bayan jirgin da aka soke ko wanda ya tafi.',
  'air-37': 'Ana amfani da ita don gaya wa ma\'aikata cewa ka rasa jirginka na haɗi saboda jinkiri.',
  'air-38': 'Ana amfani da ita don tambayar inda za a shigar da ƙara.',
  'air-39': 'Ana amfani da ita don tambaya game da mayar da kuɗin tikitinka.',
  'air-40': 'Kalmar ban kwana ce ta abokantaka da ake yi wa matafiyi kafin jirginsa.',
  'air-41': 'Ana amfani da ita don gaya wa wani fasinja da ladabi cewa yana zaune a kujerarka.',
  'air-42': 'Ana amfani da ita don neman taimakon ma\'aikacin jirgin game da akwatin kaya na sama.',
  'air-43': 'Ana amfani da ita don neman bargo yayin tafiyar jirgin.',
  'air-44': 'Ana amfani da ita don neman matashin kai yayin tafiyar jirgin.',
  'air-45': 'Ana amfani da ita don tambaya game da nau\'ukan abinci da ake da su a cikin jirgin.',
  'air-46': 'Ana amfani da ita don zaɓar wani abinci na musamman lokacin da aka kawo shi.',
  'air-47': 'Ana amfani da ita don neman ma\'aikacin jirgin kofin ruwa.',
  'air-48': 'Ana amfani da ita don tambaya game da abincin da babu nama a ciki.',
  'air-49': 'Ana amfani da ita don tambayar inda bandaki yake a cikin jirgin.',
  'air-50': 'Ana amfani da ita don tambaya ko wani na amfani da bandaki a yanzu.',
  'air-51': 'Roƙo ne na ladabi ga fasinjan gaba don ya daidaita kujerarsa.',
  'air-52': 'Ana amfani da ita don tambaya sauran lokaci nawa kafin saukar jirgin.',
  'air-53': 'Ana amfani da ita don neman a kunna fitilar karatu ta kujerarka.',
  'air-54': 'Ana amfani da ita don ba da rahoton matsala da lasifikan kunne na nishaɗi.',
  'air-55': 'Ana amfani da ita don tambaya ko akwai wurin caji a kujerarka.',
  'air-56': 'Umarni ne daga ma\'aikatan jirgin kafin tashi, sauka, ko rawar jirgin.',
  'air-57': 'Sanarwa ce daga matukin jirgi ko ma\'aikata idan jirgin yana rawa.',
  'air-58': 'Ana amfani da ita don bayyana jin haushin ciki yayin tafiyar jirgin.',
  'air-59': 'Ana amfani da ita don neman ma\'aikatan jirgin wani abu mai sauƙi na ciwon kai.',
  'air-60': 'Godiya ce ta abokantaka ga ma\'aikatan jirgin bayan tafiya mai kyau.',
  'air-61': 'Tambaya ce da ake yawan samu daga jami\'in fasfo lokacin isowa.',
  'air-62': 'Amsa ce game da dalilin ziyararka idan kai matafiyi ne na yawon buɗe ido.',
  'air-63': 'Amsa ce game da dalilin ziyararka idan kana tafiya don aiki.',
  'air-64': 'Tambaya ce daga jami\'in fasfo game da tsawon lokacin da za ka zauna.',
  'air-65': 'Amsa ce da ke bayyana yawan kwanaki ko makonnin da za ka zauna.',
  'air-66': 'Tambaya ce game da inda za ka sauka a lokacin ziyararka.',
  'air-67': 'Amsa ce da ke ambaton ko nuna otal ɗin da za ka sauka a ciki.',
  'air-68': 'Ana iya tambayarka a bincikan fasfo don tabbatar da tsare-tsaren tafiyarka.',
  'air-69': 'Tambaya ce ta farawa da ake yawan samu daga jami\'in fasfo.',
  'air-70': 'Umarni ne lokacin da ake ɗaukar hoton fasfonka a lokacin isowa.',
  'air-71': 'Umarni ne na ɗaukar yatsan hannunka a bincikan fasfo.',
  'air-72': 'Kalmar maraba ce da jami\'in fasfo ke faɗa bayan an gama aikin.',
  'air-73': 'Gaisuwa ce da ake yawan yi lokacin da ka shiga sabuwar ƙasa.',
  'air-74': 'Tambaya ce daga jami\'in kwastam game da kayan da dole a sanar da su.',
  'air-75': 'Amsa ce ga kwastam idan ba ka da wani abu da ake buƙatar sanarwa.',
  'air-76': 'Umarni ne daga jami\'in kwastam na duba abin da ke cikin jakarka.',
  'air-77': 'Ana amfani da ita don bayyana cewa kayanka ba don sayarwa ko kasuwanci ba ne.',
  'air-78': 'Ana amfani da ita don tambayar inda ƙofar fitowa ta isowa take bayan gama tsari.',
  'air-79': 'Ana amfani da ita don tambayar inda tsayawan tasi yake bayan isowa.',
  'air-80': 'Ana amfani da ita don tambaya game da tebur na hayan mota a filin jirgin.',
  'air-81': 'Ana amfani da ita don tambayar inda zauren \'yan kasuwa yake.',
  'air-82': 'Ana amfani da ita don tambaya ko kana da izinin shiga zauren baƙi na musamman.',
  'air-83': 'Ana amfani da ita don tambaya ko abinci na cikin ayyukan zauren.',
  'air-84': 'Ana amfani da ita don tambaya ko za ka iya kawo aboki cikin zauren.',
  'air-85': 'Ana amfani da ita don tambaya game da wuraren wanka a zauren.',
  'air-86': 'Ana amfani da ita don tambaya game da ɗakin da aka keɓe don hutawa ko barci.',
  'air-87': 'Ana amfani da ita don tambaya game da shiga jirgin da wuri.',
  'air-88': 'Ana amfani da ita don gaya wa ma\'aikatan filin jirgin game da matsalar lafiya mai gaggawa.',
  'air-89': 'Buƙata ce mai gaggawa don kiran likita a lokacin gaggawa.',
  'air-90': 'Ana amfani da ita don gaya wa ma\'aikata cewa ka rasa fasfonka kuma kana buƙatar taimako.',
  'air-91': 'Ana amfani da ita don gaya wa ma\'aikata cewa ka rasa jakarka ta kuɗi kuma kana buƙatar taimako.',
  'air-92': 'Ana amfani da ita don tambaya game da ofishin dawo da kayan da suka ɓace.',
  'air-93': 'Ana amfani da ita don neman taimako idan ka rabu da iyalinka.',
  'air-94': 'Ana amfani da ita don bayyana jin rashin tsaro da kuma neman taimako.',
  'air-95': 'Ana amfani da ita don tambayar inda ofishin \'yan sanda na filin jirgin yake.',
  'air-96': 'Ana amfani da ita don neman taimako wajen isa ofishin jakadancinka a lokacin gaggawa.',
  'air-97': 'Ana amfani da ita don tambaya ko akwai mai fassara idan akwai matsalar harshe.',
  'air-98': 'Ana amfani da ita don gaya wa ma\'aikaci cewa lambar jirginka ta bambanta da wadda ake tsammani.',
  'air-99': 'Godiya ce ga ma\'aikata don ci gaba da sanar da kai labari.',
  'air-100': 'Kalmar murna ce ta rufe wannan kunshin gaba ɗaya.',
};

export const quizzes = {
  'q-air-01': { question: 'Yaya za a ce "Where is the check-in counter?" a Larabci?', explain: '"Where is the check-in counter?" na nufin "أين مكتب تسجيل الوصول؟" a Larabci.' },
  'q-air-03': { question: 'Yaya za a ce "Where is my gate?" a Larabci?', explain: '"Where is my gate?" na nufin "أين بوابة الصعود الخاصة بي؟" a Larabci.' },
  'q-air-05': { question: 'Yaya za a ce "Where is passport control?" a Larabci?', explain: '"Where is passport control?" na nufin "أين مكتب مراقبة الجوازات؟" a Larabci.' },
  'q-air-07': { question: 'Yaya za a ce "Where is baggage claim?" a Larabci?', explain: '"Where is baggage claim?" na nufin "أين تسليم الأمتعة؟" a Larabci.' },
  'q-air-08': { question: 'Yaya za a ce "My luggage is missing." a Larabci?', explain: '"My luggage is missing." na nufin "حقيبتي مفقودة." a Larabci.' },
  'q-air-09': { question: 'Yaya za a ce "What time does boarding start?" a Larabci?', explain: '"What time does boarding start?" na nufin "متى يبدأ الصعود إلى الطائرة؟" a Larabci.' },
  'q-air-11': { question: 'Yaya za a ce "Is my flight delayed?" a Larabci?', explain: '"Is my flight delayed?" na nufin "هل رحلتي متأخرة؟" a Larabci.' },
  'q-air-12': { question: 'Yaya za a ce "I would like a window seat, please." a Larabci?', explain: '"I would like a window seat, please." na nufin "أريد مقعدًا بجانب النافذة من فضلك." a Larabci.' },
  'q-air-17': { question: 'Yaya za a ce "Can I get a new boarding pass?" a Larabci?', explain: '"Can I get a new boarding pass?" na nufin "هل يمكنني الحصول على بطاقة صعود جديدة؟" a Larabci.' },
  'q-air-18': { question: 'Yaya za a ce "Where is the duty-free shop?" a Larabci?', explain: '"Where is the duty-free shop?" na nufin "أين محلات السوق الحرة؟" a Larabci.' },
  'q-air-21': { question: 'Yaya za a ce "Is there a shuttle bus to the terminal?" a Larabci?', explain: '"Is there a shuttle bus to the terminal?" na nufin "هل يوجد حافلة مكوكية إلى الصالة؟" a Larabci.' },
  'q-air-24': { question: 'Yaya za a ce "Is there free Wi-Fi here?" a Larabci?', explain: '"Is there free Wi-Fi here?" na nufin "هل يوجد واي فاي مجاني هنا؟" a Larabci.' },
  'q-air-26': { question: 'Yaya za a ce "I need to declare this item." a Larabci?', explain: '"I need to declare this item." na nufin "أحتاج إلى التصريح عن هذا الغرض." a Larabci.' },
  'q-air-31': { question: 'Yaya za a ce "I need a wheelchair, please." a Larabci?', explain: '"I need a wheelchair, please." na nufin "أحتاج إلى كرسي متحرك من فضلك." a Larabci.' },
  'q-air-33': { question: 'Yaya za a ce "Can my child sit next to me?" a Larabci?', explain: '"Can my child sit next to me?" na nufin "هل يمكن أن يجلس طفلي بجانبي؟" a Larabci.' },
  'q-air-35': { question: 'Yaya za a ce "My flight was cancelled." a Larabci?', explain: '"My flight was cancelled." na nufin "تم إلغاء رحلتي." a Larabci.' },
  'q-air-36': { question: 'Yaya za a ce "Can you rebook me on the next flight?" a Larabci?', explain: '"Can you rebook me on the next flight?" na nufin "هل يمكنك إعادة حجزي على الرحلة التالية؟" a Larabci.' },
  'q-air-39': { question: 'Yaya za a ce "Can I get a refund for this ticket?" a Larabci?', explain: '"Can I get a refund for this ticket?" na nufin "هل يمكنني استرداد ثمن هذه التذكرة؟" a Larabci.' },
  'q-air-41': { question: 'Yaya za a ce "Excuse me, this is my seat." a Larabci?', explain: '"Excuse me, this is my seat." na nufin "عذرًا، هذا مقعدي." a Larabci.' },
  'q-air-45': { question: 'Yaya za a ce "What is on the menu today?" a Larabci?', explain: '"What is on the menu today?" na nufin "ماذا يوجد في قائمة الطعام اليوم؟" a Larabci.' },
  'q-air-47': { question: 'Yaya za a ce "Can I have water, please?" a Larabci?', explain: '"Can I have water, please?" na nufin "هل يمكنني الحصول على ماء من فضلك؟" a Larabci.' },
  'q-air-49': { question: 'Yaya za a ce "Where is the restroom?" a Larabci?', explain: '"Where is the restroom?" na nufin "أين دورة المياه؟" a Larabci.' },
  'q-air-52': { question: 'Yaya za a ce "How much longer until we land?" a Larabci?', explain: '"How much longer until we land?" na nufin "كم تبقى حتى الهبوط؟" a Larabci.' },
  'q-air-56': { question: 'Yaya za a ce "Please fasten your seatbelt." a Larabci?', explain: '"Please fasten your seatbelt." na nufin "يرجى ربط حزام الأمان." a Larabci.' },
  'q-air-58': { question: 'Yaya za a ce "I feel airsick." a Larabci?', explain: '"I feel airsick." na nufin "أشعر بدوار الطيران." a Larabci.' },
  'q-air-61': { question: 'Yaya za a ce "What is the purpose of your visit?" a Larabci?', explain: '"What is the purpose of your visit?" na nufin "ما هو الغرض من زيارتك؟" a Larabci.' },
  'q-air-64': { question: 'Yaya za a ce "How long will you be staying?" a Larabci?', explain: '"How long will you be staying?" na nufin "كم ستبقى مدة إقامتك؟" a Larabci.' },
  'q-air-68': { question: 'Yaya za a ce "Do you have a return ticket?" a Larabci?', explain: '"Do you have a return ticket?" na nufin "هل لديك تذكرة عودة؟" a Larabci.' },
  'q-air-74': { question: 'Yaya za a ce "Do you have anything to declare?" a Larabci?', explain: '"Do you have anything to declare?" na nufin "هل لديك شيء تريد التصريح عنه؟" a Larabci.' },
  'q-air-75': { question: 'Yaya za a ce "I have nothing to declare." a Larabci?', explain: '"I have nothing to declare." na nufin "ليس لدي شيء أُصرّح عنه." a Larabci.' },
  'q-air-79': { question: 'Yaya za a ce "Where can I get a taxi?" a Larabci?', explain: '"Where can I get a taxi?" na nufin "أين يمكنني الحصول على تاكسي؟" a Larabci.' },
  'q-air-80': { question: 'Yaya za a ce "Where is the car rental counter?" a Larabci?', explain: '"Where is the car rental counter?" na nufin "أين مكتب تأجير السيارات؟" a Larabci.' },
  'q-air-81': { question: 'Yaya za a ce "Where is the business lounge?" a Larabci?', explain: '"Where is the business lounge?" na nufin "أين صالة رجال الأعمال؟" a Larabci.' },
  'q-air-84': { question: 'Yaya za a ce "Can I bring a guest to the lounge?" a Larabci?', explain: '"Can I bring a guest to the lounge?" na nufin "هل يمكنني اصطحاب ضيف إلى الصالة؟" a Larabci.' },
  'q-air-88': { question: 'Yaya za a ce "I have a medical emergency." a Larabci?', explain: '"I have a medical emergency." na nufin "لدي حالة طوارئ طبية." a Larabci.' },
  'q-air-90': { question: 'Yaya za a ce "I lost my passport." a Larabci?', explain: '"I lost my passport." na nufin "فقدت جواز سفري." a Larabci.' },
  'q-air-92': { question: 'Yaya za a ce "Where is the lost and found office?" a Larabci?', explain: '"Where is the lost and found office?" na nufin "أين مكتب المفقودات؟" a Larabci.' },
  'q-air-95': { question: 'Yaya za a ce "Where is the police station?" a Larabci?', explain: '"Where is the police station?" na nufin "أين مركز الشرطة؟" a Larabci.' },
  'q-air-96': { question: 'Yaya za a ce "I need to contact my embassy." a Larabci?', explain: '"I need to contact my embassy." na nufin "أحتاج للتواصل مع سفارتي." a Larabci.' },
  'q-air-98': { question: 'Yaya za a ce "My flight number has changed." a Larabci?', explain: '"My flight number has changed." na nufin "تغير رقم رحلتي." a Larabci.' },
};
